'use client';

import * as React from 'react';
import { CalendarDays, Check, X } from 'lucide-react';
import { formatCurrency } from '@/lib/utils';

type Occurrence = { id: string; name: string; description?: string; amount: number; paidAmount: number; dueDate: string; status: 'pendente' | 'paga' | 'parcial' | 'cancelada' | 'atrasada'; type: 'receita' | 'despesa'; paymentMethod: string };
const labels = { pendente: 'Pendente', paga: 'Paga', parcial: 'Parcial', cancelada: 'Cancelada', atrasada: 'Atrasada' } as const;

export default function MonthlyBillsPage() {
  const [competence, setCompetence] = React.useState(() => new Date().toISOString().slice(0, 7));
  const [status, setStatus] = React.useState(''); const [items, setItems] = React.useState<Occurrence[]>([]); const [loading, setLoading] = React.useState(true); const [message, setMessage] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { setLoading(true); try { const query = new URLSearchParams({ competence }); if (status) query.set('status', status); const response = await fetch(`/api/finance/fixed-account-occurrences?${query}`); const data = await response.json() as { success: boolean; occurrences?: Occurrence[]; message?: string }; if (!response.ok || !data.success) throw new Error(data.message ?? 'Não foi possível carregar as ocorrências.'); setItems(data.occurrences ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao carregar.'); } finally { setLoading(false); } }, [competence, status]);
  React.useEffect(() => { void load(); }, [load]);
  async function action(id: string, action: 'pay' | 'cancel'): Promise<void> { if (action === 'cancel' && !window.confirm('Cancelar esta ocorrência? O histórico será preservado.')) return; const response = await fetch(`/api/finance/fixed-account-occurrences/${id}/${action}`, { method: 'POST', headers: action === 'pay' ? { 'Idempotency-Key': crypto.randomUUID() } : undefined }); const data = await response.json() as { success: boolean; message?: string }; setMessage(data.message ?? (data.success ? 'Atualizado.' : 'Não foi possível atualizar.')); if (data.success) await load(); }
  return <main className="mx-auto w-full max-w-6xl px-5 py-8 sm:px-8"><header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent-blue">Financeiro</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-text-primary">Contas do mês</h1><p className="mt-2 text-sm text-text-secondary">Ocorrências reais e imutáveis das suas contas recorrentes.</p></header><div className="mb-5 flex flex-wrap gap-3"><input type="month" value={competence} onChange={(event) => setCompetence(event.target.value)} className="rounded-lg border border-border-subtle bg-surface-1 px-3 py-2 text-sm text-text-primary" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-border-subtle bg-surface-1 px-3 py-2 text-sm text-text-primary"><option value="">Todos os status</option><option value="pendente">Pendentes</option><option value="atrasada">Atrasadas</option><option value="paga">Pagas</option><option value="parcial">Parciais</option></select></div>{message && <p className="mb-4 rounded-lg bg-tint/[0.04] px-3 py-2 text-sm text-text-secondary">{message}</p>}<section className="overflow-hidden rounded-2xl border border-border-subtle bg-surface-1">{loading ? <p className="p-6 text-sm text-text-secondary">Carregando ocorrências…</p> : items.length === 0 ? <div className="p-10 text-center"><CalendarDays className="mx-auto h-6 w-6 text-accent-blue" /><p className="mt-3 font-medium text-text-primary">Nenhuma conta para este período</p></div> : <div className="divide-y divide-border-subtle">{items.map((item) => <article key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-text-primary">{item.name}</p><p className="mt-1 text-sm text-text-secondary">Vence em {new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(item.dueDate))} · {labels[item.status]}</p></div><div className="flex items-center gap-3"><span className={item.type === 'despesa' ? 'font-semibold text-accent-red' : 'font-semibold text-accent-green'}>{formatCurrency(item.amount)}</span>{(item.status === 'pendente' || item.status === 'atrasada' || item.status === 'parcial') && <button onClick={() => void action(item.id, 'pay')} className="inline-flex items-center gap-1 rounded-lg bg-accent-green px-3 py-2 text-sm font-medium text-black"><Check className="h-4 w-4" /> Pagar</button>}{item.status === 'pendente' && <button onClick={() => void action(item.id, 'cancel')} className="rounded-lg p-2 text-text-secondary hover:bg-tint/[0.06]"><X className="h-4 w-4" /></button>}</div></article>)}</div>}</section></main>;
}
